name: Weekly Python Script Run

on:
  schedule:
    # This cron job runs at 00:00 every Sunday
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script and capture output
        id: script
        run: |
          output=$(python main.py 2>&1 | sed 's/\x1b\[[0-9;]*m//g')
          output="${output//'%'/'%25'}"  # Escape %
          output="${output//$'\n'/'<br/>'}"  # Escape newlines
          output="${output//$'\r'/'%0D'}"  # Escape carriage returns
          echo "::set-output name=result::$output"

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Create Issue
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: |
            [Weekly Event Report] Date: ${{ steps.date.outputs.date }}
          assignees: ${{ github.actor }},${{ github.triggering_actor }}
          labels: automated-issue
          body: |
            ${{ steps.script.outputs.result }}

